name: Lottery Auto Update

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          pip install pandas requests openpyxl python-docx TaiwanLottery

      - name: Run Program
        run: |
          python 539.py

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Auto Update" || echo "No changes"

      - name: Push Files
        run: |
          git push
